integrate_tests:
  description: >

    framework:
    ```{framework}```
    original_test_code:
    ```{original_test_code}```
    generated_tests_code:
    ```{generated_tests_code}```
    available_fixtures:
    ```{available_fixtures}```
    =====================================

    Merge newly generated unit tests into the target test file, preserving and reusing
    existing structure, classes, and fixtures. Ensure imports and style are consistent.

    Rules:
      - Generate MINIMAL and correct unified diff (patch) against the current file.
      - Reuse fixtures and group tests under a single class when appropriate.
      - Generate fixtures for new tests if the performance of the new tests can be improved.
      - Remove an existing test ONLY if new changes make it directly obsolete.

    Rules for the diff:
      - Output MUST be a valid unified diff with correct headers and context.
      - Do not output full file content, only the diff hunks.

  expected_output: >
    A JSON list of objects: [{"path": str, "content_diff": str}]
  agent: tests_integrator


