summarize_modules:
  description: >-
    invidual_summaries:
    ```{invidual_summaries}```

    ------------------------------------------------------------

    Goal:
    Produce one highlevel JSON overview per toplevel package/folder using ONLY the provided summaries.

    Rules:
      - Use English in all outputs.
      - Return compact JSON (minified; no extra spaces or newlines).
      - Do not invent folders, files, classes, functions, or dependencies.
      - If a value is unknown, use "" for strings or [] for arrays.
      - Truncate any description to <= 180 characters.
      - Keep keys exactly as specified.
      - Do not include versions for dependencies.

    Guidance:
      - Infer packages/folders by grouping files by their top-level directories within the
        chunk; do not invent folders that are not present.
      - Keep overviews concise, focusing on responsibilities, interfaces, and relationships.

    First, think through the necessary logic and data. Then, in a second step, generate only the JSON object.

  expected_output: >-
    Output JSON:
      {
        "location": "import route of the module (e.g. 'project.module')",
        "purpose": "Deatiled but concise description of the module's purpose and responsibilities",
        "structure_tree": [
            "folder/",
            "├── subfolder_1/ # Brief description",
            "│   ├── file_1.py # Purpose",
            "│   └── file_2.py # Purpose",
            "├── subfolder_2/ # Brief description",
            "│   └── file_3.py # Purpose",
            "└── __init__.py # Purpose"
        ],
        "dependencies": {
          "internal": [{"path": "module_1.py", "reason": "Why it is used"}],
          "external": [{"name": "external_library", "purpose": "What for"}]
        },
        "interfaces": {
          "classes": [{"name": "project.module.MainClass", "description": "Short description", "methods": [{"name": "method_name", "signature": "method_name(arg: type) -> return_type", "description": "Short description"}]}],
          "functions": [{"name": "project.module.public_function", "signature": "public_function()", "description": "Short description"}]
        },
        "workflows": ["Describe key flows or processes implemented by this module"],
        "notes": "Technical details relevant for development"
      }
    Return only valid JSON. Do not add prose outside JSON.
  agent: module_summarizer
