summarize_modules:
  description: >-
    invidual_summaries:
    ```{invidual_summaries}```

    ------------------------------------------------------------

    Task:
    Generate one high-level JSON overview per package/folder from the information of
    the individual summaries provided. Use ONLY the provided JSON structure.

    Guidance:
      - Infer packages/folders by grouping files by their top-level directories within the
        chunk; do not invent folders that are not present.
      - Keep overviews concise, focusing on responsibilities, interfaces, and relationships.
      - Use English in all outputs.

  expected_output: >-
    Output JSON:
      {
        "location": "import route of the module (e.g. 'project.module')",
        "purpose": "Deatiled but concise description of the module's purpose and responsibilities",
        "structure_tree": [
            "folder/",
            "├── subfolder_1/ # Brief description",
            "│   ├── file_1.py # Purpose",
            "│   └── file_2.py # Purpose",
            "├── subfolder_2/ # Brief description",
            "│   └── file_3.py # Purpose",
            "└── __init__.py # Purpose"
        ],
        "dependencies": {
          "internal": [{"path": "module_1.py", "reason": "Why it is used"}],
          "external": [{"name": "external_library", "purpose": "What for"}]
        },
        "interfaces": {
          "classes": [{"name": "project.module.MainClass", "description": "Short description", "methods": [{"name": "method_name", "signature": "method_name(arg: type) -> return_type", "description": "Short description"}]}],
          "functions": [{"name": "project.module.public_function", "signature": "public_function()", "description": "Short description"}]
        },
        "workflows": ["Describe key flows or processes implemented by this module"],
        "notes": "Technical details relevant for development"
      }
    Return only valid JSON. Do not add prose outside JSON.
  agent: module_summarizer
