locate_summaries_dir:
  description: >-

    Inputs:
      - src_dir: the absolute path to the repository's source directory
      - docs_dir: the absolute path to the documentation directory, or null
      - test_dirs: a JSON array of absolute paths to test directories

      src_dir:
      ```{src_dir}```
      docs_dir:
      ```{docs_dir}```
      test_dirs:
      ```{test_dirs}```

    Task:
      Decide a single absolute path where Markdown summaries should be stored.
      Prefer the repository root 'summaries' directory adjacent to src_dir's root and
      docs_dir's root if it exists.

      The path must be absolute, normalized, and deterministic. Do not invent nested
      folders beyond 'summaries'. Do not place summaries inside test directories.

    Example:
      repo = /abs/path/proj
      src_dir = /abs/path/proj/src
      docs_dir = /abs/path/proj/docs
      test_dirs = ["/abs/path/proj/tests"]
      Output: {"summaries_dir": "/abs/path/proj/summaries"}

  expected_output: >-
    Output JSON:
      {
        "summaries_dir": str
      }
    Return only valid JSON. Do not add prose outside JSON.
  agent: locator
