produce_rename_map:
  description: >-
    You are given a JSON description containing rename specifications.
    Your job is to return a deterministic JSON object mapping each original
    file path to its new path: {"old_path": "new_path"} per entry.

    Normalize the result into a single flat JSON object where keys are old paths
    and values are new paths. Do not include duplicates; the last occurrence wins.

    IMPORTANT:
      - Do not add prose. Output JSON only.
      - Do not infer non-provided paths.
      - Preserve paths exactly as given (do not resolve to absolute).
  expected_output: >-
    Output JSON:
      {"old_path": "new_path"}
  agent: mapper
