generate_diffs:
  description: >
    Instructions:
    `{instructions}`
    File code:
    `{file_code}`
    Source code directory:
    `{src_dir}`

    Given a mapping of file paths to their current contents, generate minimal,
    safe unified diffs (patches) to implement the requested changes. Prefer
    localized edits. Don't produce complete file contents.

    The diff MUST be a valid unified diff applying to the given file path, with
    correct file headers and context. If no change is needed for a file, omit it.
    The unified diff headers MUST use the form `--- a/[relative_path]` and
    `+++ b/[relative_path]`, where `[relative_path]` is the path of the file
    relative to `{src_dir}` (no leading slash, and do not include `{src_dir}`).

    Details per item:
      - path: relative path to the file being changed
      - content_diff: unified diff to apply

  expected_output: >
    Output JSON format:
    {
      "root": [{
        "path": str,
        "content_diff": str
      }]
    }
    IMPORTANT: The path output must be absolute under the source code directory.
    Use compact language. Do not add prose outside JSON.
  agent: code_diff_generator
