generate_diffs:
  description: >
    Instructions:
    `{instructions}`
    File code:
    `{file_code}`
    Source code directory:
    `{src_dir}`

    Given a mapping of file paths to their current contents, generate minimal,
    safe unified diffs (patches) to implement the requested changes. Prefer
    localized edits. Don't produce complete file contents.

    The diff MUST be a valid unified diff applying to the given file path, with
    correct file headers and context. If no change is needed for a file, omit it.

    Details per item:
      - path: relative path to the file being changed
      - content_diff: unified diff to apply

    IMPORTANT: The path must be absolute under the source code directory.

  expected_output: >
    Output JSON format:
    {
      "root": [{
        "path": str,
        "content_diff": str
      }]
    }
    Use compact language. Do not add prose outside JSON.
  agent: code_diff_generator
