produce_copy_map:
  description: >-
    You are given a JSON description containing copy specifications.
    Return a deterministic JSON object mapping each source file path to
    its destination path: {"old_path": "new_path"} per entry.

    Normalize the result into a single flat JSON object where keys are source paths
    and values are destination paths. Do not include duplicates; the last occurrence wins.

    IMPORTANT:
      - Output JSON only, no prose.
      - Do not infer paths.
      - Preserve the paths as provided (no absolute resolution).
  expected_output: >-
    Output JSON:
      {"old_path": "new_path"}
  agent: mapper
