select_relevant_files:
  description: >-
    user_prompt:
    ```{user_prompt}```

    module_summaries:
    ```json
    {module_summaries}
    ```

    Task:
    Based on the user's prompt and the set of per-module summaries
    (no source code), return an array of file paths (.py) from the module
    structure that are relevant to addressing the prompt.

    Requirements:
      - Do not care about missing dependencies, just the project code relevant to the prompt.
      - In case of doubt, include the file.
      - Do NOT include __init__.py files.

    IMPORTANT: The output file paths must be absolute. The project source code is in the folder {src_dir}.

  expected_output: >-
    Output JSON:
      [str]
    Return only valid JSON. Do not add prose outside JSON.
  agent: analyst

classify_file_detail:
  description: >-
    user_prompt:
    ```{user_prompt}```

    relevant_file_summaries:
    ```json
    {relevant_file_summaries}
    ```

    Task:
    Given the user's prompt and the JSON map of relevant file summaries
    (path -> markdown content), divide the files into two sets:
    - summaries_only: summaries are sufficient to plan at high confidence
    - need_code: reading the file source code is required to plan accurately

    Guidance:
      - Prefer summaries_only when the summary contains clear public APIs,
        invariants, and usage notes adequate for planning.
      - Prefer need_code when behavior, side-effects, or contracts are unclear.

    IMPORTANT: The size of the final lists can be smaller than the original sets
    because some files may be irrelevant to the prompt. Empty lists are valid.

  expected_output: >-
    Output JSON:
      {
        "summaries_only": [str],
        "need_code": [str]
      }
    Return only valid JSON. Do not add prose outside JSON.
  agent: classifier

produce_action_plan:
  description: >-
    project_files:
    ```
    {file_list}
    ```

    user_prompt:
    ```{user_prompt}```

    summaries:
    ```json
    {summaries}
    ```

    code:
    ```json
    {code}
    ```

    Task:
    Produce an actionable, detailed step-by-step plan to fulfill the user's
    request. Use only the provided context (summaries and code excerpts when
    present).

    Requirements:
      - The plan MUST be a recipe of steps, not code.
      - Keep steps small, testable, and logically sequenced.
      - Do NOT define file references that are not coherent with the project structure.
      - Only refer to the project source code, do NOT refer on how the project will be used.
      - Only empty files can be created. The content should be added later.

    Each step should be properly detailed to be executed independently. The plan
    will be carried out in order.

    ALLOWED STEP TYPES:
      - Modify code
      - Create new file
      - Delete file
      - Rename file
      - Move file
      - Copy file
      - Create new directory
      - Delete directory

    Details:
      - points: Deeply-reasoned implementation effort of the classes and functions:
          * 1 for tasks that can be implemented by a junior developer.
          * 2 for tasks that require a senior developer.
          * 3 for tasks that require a lead developer.

    IMPORTANT:
      - The output file paths must be absolute. The project source code is in the folder {src_dir}.
      - Do NOT include steps related to git, testing, documentation, etc.
      - KEEP A REDUCED NUMBER OF STEPS.

  expected_output: >-
    Output JSON:
      [
        {"step": int, "title": str, "description": str, "path": str, "type": str, points: int}
      ]
    Return only valid JSON. Do not add prose outside JSON. Use ENGLISH.
  agent: planner
